#!/usr/bin/env bash
# Regenerate the agent catalog table in agent/AGENTS.md from agent/agents/*.md frontmatter.
#
# Reads `name` and `description` from each agent file's YAML frontmatter and emits
# a markdown table between two marker comments in AGENTS.md. Idempotent.

set -euo pipefail

MODE="write"
case "${1:-}" in
  --check) MODE="check" ;;
  -h|--help)
    echo "usage: $0 [--check]"
    echo "  (default) regenerate agent catalog in agent/AGENTS.md"
    echo "  --check   exit 0 if AGENTS.md matches regenerated output, 1 on drift or env error"
    exit 0 ;;
  "") ;;
  *) echo "error: unknown flag: $1 (try --help)" >&2; exit 2 ;;
esac

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENTS_DIR="${REPO_DIR}/agent/agents"
AGENTS_MD="${REPO_DIR}/agent/AGENTS.md"

BEGIN_MARKER="<!-- BEGIN agent-catalog (generated by scripts/regen-agent-catalog.sh) -->"
END_MARKER="<!-- END agent-catalog -->"

if [ ! -d "${AGENTS_DIR}" ]; then
  echo "error: ${AGENTS_DIR} not found" >&2
  exit 1
fi
if [ ! -f "${AGENTS_MD}" ]; then
  echo "error: ${AGENTS_MD} not found" >&2
  exit 1
fi

# Build the table rows from frontmatter.
table_rows=""
for f in "${AGENTS_DIR}"/*.md; do
  [ -f "${f}" ] || continue
  # Extract the YAML block between the first pair of `---` lines.
  fm="$(awk '/^---$/{c++; next} c==1{print} c==2{exit}' "${f}")"
  name="$(printf '%s\n' "${fm}" | sed -nE 's/^name: *"?([^"]+)"?[[:space:]]*$/\1/p' | head -n1)"
  # Greedy `(.+)` is intentional so descriptions containing `"` round-trip;
  # the trailing-quote trim below normalizes the closing quote (if any).
  # We do not escape `|` here — frontmatter `description:` values must not
  # contain raw `|`, since the value is interpolated into a markdown table
  # column. Surface this as an explicit warning rather than corrupting the
  # table silently.
  desc="$(printf '%s\n' "${fm}" | sed -nE 's/^description: *"?(.+)"?[[:space:]]*$/\1/p' | head -n1)"
  mode="$(printf '%s\n' "${fm}" | sed -nE 's/^mode: *"?([a-z-]+)"?[[:space:]]*$/\1/p' | head -n1)"
  # Trim a trailing quote that the regex above may have left in place.
  desc="${desc%\"}"
  case "${desc}" in
    *\|*)
      echo "warn: ${f} description contains '|' which would break the catalog table column; skipping" >&2
      continue
      ;;
  esac
  if [ -z "${name}" ] || [ -z "${desc}" ]; then
    echo "warn: skipping ${f} (missing name or description in frontmatter)" >&2
    continue
  fi
  if [ -z "${mode}" ]; then
    mode="interactive"
    echo "warn: ${f} has no 'mode:' field; defaulting to 'interactive'" >&2
  fi
  table_rows+="| \`${name}\` | ${mode} | ${desc} |"$'\n'
done

if [ -z "${table_rows}" ]; then
  echo "error: no valid agent files found in ${AGENTS_DIR}" >&2
  exit 1
fi

# Build the new block.
new_block="${BEGIN_MARKER}
| Agent | Mode | Description |
|---|---|---|
${table_rows}${END_MARKER}"

# Replace between markers using awk for portability.
# Note: pass the multi-line block via a temp file (read with `getline`) rather
# than `-v block=...`. BSD awk on macOS rejects multi-line `-v` values with
# "newline in string".
tmp="$(mktemp)"
block_file="$(mktemp)"
trap 'rm -f "${tmp}" "${block_file}"' EXIT
printf '%s\n' "${new_block}" > "${block_file}"
awk -v begin="${BEGIN_MARKER}" -v end="${END_MARKER}" -v blockfile="${block_file}" '
  $0 == begin {
    while ((getline line < blockfile) > 0) print line
    close(blockfile)
    in_block = 1
    next
  }
  $0 == end { in_block = 0; next }
  !in_block { print }
' "${AGENTS_MD}" > "${tmp}"

# Verify markers existed (awk would have produced no `block` output if begin marker missing).
if ! grep -qF "${BEGIN_MARKER}" "${tmp}"; then
  echo "error: could not find ${BEGIN_MARKER} in ${AGENTS_MD}; aborting" >&2
  exit 1
fi

if [ "${MODE}" = "check" ]; then
  # Print unified diff on stderr so callers see *what* drifted; exit 1 on drift.
  diff -u "${AGENTS_MD}" "${tmp}" >&2 || exit 1
  exit 0
fi

mv "${tmp}" "${AGENTS_MD}"
echo "regenerated agent catalog in ${AGENTS_MD} ($(printf '%s' "${table_rows}" | wc -l | tr -d ' ') agents)"
